export const cards = [
  {
    id: 1,
    value: "A",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_a.svg",
  },
  {
    id: 2,
    value: "2",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_2.svg",
  },
  {
    id: 3,
    value: "3",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_3.svg",
  },
  {
    id: 4,
    value: "4",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_4.svg",
  },
  {
    id: 5,
    value: "5",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_5.svg",
  },
  {
    id: 6,
    value: "6",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_6.svg",
  },
  {
    id: 7,
    value: "7",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_7.svg",
  },
  {
    id: 8,
    value: "8",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_8.svg",
  },
  {
    id: 9,
    value: "9",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_9.svg",
  },
  {
    id: 10,
    value: "10",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_10.svg",
  },
  {
    id: 11,
    value: "J",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_j.svg",
  },
  {
    id: 12,
    value: "Q",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_q.svg",
  },
  {
    id: 13,
    value: "K",
    suit: "♦",
    color: "red",
    src: "/img/cards/diamond_k.svg",
  },
  {
    id: 14,
    value: "A",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_a.svg",
  },
  {
    id: 15,
    value: "2",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_2.svg",
  },
  {
    id: 16,
    value: "3",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_3.svg",
  },
  {
    id: 17,
    value: "4",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_4.svg",
  },
  {
    id: 18,
    value: "5",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_5.svg",
  },
  {
    id: 19,
    value: "6",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_6.svg",
  },
  {
    id: 20,
    value: "7",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_7.svg",
  },
  {
    id: 21,
    value: "8",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_8.svg",
  },
  {
    id: 22,
    value: "9",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_9.svg",
  },
  {
    id: 23,
    value: "10",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_10.svg",
  },
  {
    id: 24,
    value: "J",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_j.svg",
  },
  {
    id: 25,
    value: "Q",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_q.svg",
  },
  {
    id: 26,
    value: "K",
    suit: "♥",
    color: "red",
    src: "/img/cards/heart_k.svg",
  },
  {
    id: 27,
    value: "A",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_a.svg",
  },
  {
    id: 28,
    value: "2",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_2.svg",
  },
  {
    id: 29,
    value: "3",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_3.svg",
  },
  {
    id: 30,
    value: "4",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_4.svg",
  },
  {
    id: 31,
    value: "5",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_5.svg",
  },
  {
    id: 32,
    value: "6",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_6.svg",
  },
  {
    id: 33,
    value: "7",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_7.svg",
  },
  {
    id: 34,
    value: "8",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_8.svg",
  },
  {
    id: 35,
    value: "9",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_9.svg",
  },
  {
    id: 36,
    value: "10",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_10.svg",
  },
  {
    id: 37,
    value: "J",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_j.svg",
  },
  {
    id: 38,
    value: "Q",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_q.svg",
  },
  {
    id: 39,
    value: "K",
    suit: "♠",
    color: "black",
    src: "/img/cards/spade_k.svg",
  },
  {
    id: 40,
    value: "A",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_a.svg",
  },
  {
    id: 41,
    value: "2",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_2.svg",
  },
  {
    id: 42,
    value: "3",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_3.svg",
  },
  {
    id: 43,
    value: "4",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_4.svg",
  },
  {
    id: 44,
    value: "5",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_5.svg",
  },
  {
    id: 45,
    value: "6",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_6.svg",
  },
  {
    id: 46,
    value: "7",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_7.svg",
  },
  {
    id: 47,
    value: "8",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_8.svg",
  },
  {
    id: 48,
    value: "9",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_9.svg",
  },
  {
    id: 49,
    value: "10",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_10.svg",
  },
  {
    id: 50,
    value: "J",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_j.svg",
  },
  {
    id: 51,
    value: "Q",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_q.svg",
  },
  {
    id: 52,
    value: "K",
    suit: "♣",
    color: "black",
    src: "/img/cards/club_k.svg",
  },
  {
    id: 53,
    value: "Joker",
    suit: "J1",
    color: "black",
    src: "/img/cards/joker_1.svg",
  },
  {
    id: 54,
    value: "Joker",
    suit: "J2",
    color: "black",
    src: "/img/cards/joker_2.svg",
  },
];
